spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: 2726
  flyway:
    baseline-on-migrate: true


